# Generated by Django 5.2.3 on 2025-07-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeElection',
            fields=[
                ('id_type_election', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id_election', models.AutoField(primary_key=True, serialize=False)),
                ('nb_candidat_inscrit', models.PositiveIntegerField(default=0)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField(editable=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('tourActuel', models.PositiveIntegerField(default=1, editable=False)),
                ('seuilMajorite', models.PositiveIntegerField(default=50, editable=False)),
                ('status', models.CharField(choices=[('En préparation', 'En préparation'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='En préparation', max_length=20)),
                ('type_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='elections.typeelection')),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id_candidat', models.AutoField(primary_key=True, serialize=False)),
                ('numCandidat', models.PositiveIntegerField()),
                ('pseudo', models.CharField(blank=True, max_length=100, null=True)),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
                ('biographie', models.TextField()),
                ('photo_candidat', models.ImageField(upload_to='images/candidats/')),
                ('estQualifieTour2', models.BooleanField(default=False)),
                ('id_electeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electeurs.electeur')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='elections.election')),
            ],
            options={
                'unique_together': {('election', 'numCandidat')},
            },
        ),
    ]
