# Generated by Django 5.2.3 on 2025-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('En préparation', 'En préparation'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='En préparation', max_length=20),
        ),
    ]
