# Generated by Django 5.2.3 on 2025-07-30 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id_district', models.AutoField(primary_key=True, serialize=False)),
                ('nom_district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='electeurs.district')),
            ],
            options={
                'unique_together': {('nom_commune', 'district')},
            },
        ),
        migrations.CreateModel(
            name='Fokontany',
            fields=[
                ('id_fokontany', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fokontany', models.CharField(max_length=100)),
                ('nb_electeur_inscrit', models.PositiveIntegerField(default=0)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fokontanys', to='electeurs.commune')),
            ],
            options={
                'unique_together': {('nom_fokontany', 'commune')},
            },
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_electeur', models.CharField(max_length=100)),
                ('prenom_electeur', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('numCIN', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='Le numéro CIN doit comporter exactement 12 chiffres.')])),
                ('adresse', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/electeurs/')),
                ('numTel', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', message='Le numéro de téléphone doit commencer par 0 et contenir 10 chiffres.')])),
                ('fokontany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electeurs', to='electeurs.fokontany')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='electeurs.region'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('nom_district', 'region')},
        ),
    ]
